services:
  ai_recruiter:
    build: .
    container_name: ai_recruiter
    volumes:
      - ./resume_collection:/app/resume_collection  # Mount the resume collection folder
    user: "${UID:-1000}:${GID:-1000}"  # Map container user to host user
    env_file:
      - .env  # Load environment variables
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    command: uvicorn fastapi_server:app --host 0.0.0.0 --port 8000 --reload


  resume_generator:
    build: .
    container_name: resume_generator
    volumes:
      - ./resume_collection:/app/resume_collection  # Mount the resume collection folder
    user: "${UID:-1000}:${GID:-1000}"  # Map container user to host user
    command: python generate_resumes.py  # Run the resume generation script
    profiles:
      - generator
